apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: p94h1ao0l-python 
  janus-idp.io/tekton: p94h1ao0l-python
  backstage.io/kubernetes-id: p94h1ao0l-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: p94h1ao0l-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml